source "https://rubygems.org"

gemspec

gem "octicons"
if (rails_version = ENV["RAILS_VERSION"])
  gem "rails", "~> #{rails_version}"
end

group :development, :test do
  gem "minitest"
  gem "rake"
  gem "rubocop"
  gem "rubocop-github"
end
